!Copyright (c) 2018, Miha Polajnar
!All rights reserved.
!
!Redistribution and use in source and binary forms, with or without
!modification, are permitted provided that the following conditions are met:
!    * Redistributions of source code must retain the above copyright
!      notice, this list of conditions and the following disclaimer.
!    * Redistributions in binary form must reproduce the above copyright
!      notice, this list of conditions and the following disclaimer in the
!      documentation and/or other materials provided with the distribution.
!    * Neither the name of the <organization> nor the
!      names of its contributors may be used to endorse or promote products
!      derived from this software without specific prior written permission.
!
!THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
!ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
!WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
!DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
!DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
!(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
!LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
!ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
!(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
!SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


!
! CHANGES
! 19.12.2018 - Miha Polajnar
! Started
!


module lbfgsb_al
  use iso_fortran_env, only: rk => real64 ! Only for double precision
  use l_bfgs_b_orig, only: setulb
  implicit none
  private

  interface
    real(rk) pure function func_intrf(x,arg)
      import :: rk
      real(rk), intent(in) :: x(:)
      class(*), intent(in) :: arg
    end function
    pure subroutine grad_intrf(x,arg,g)
      import :: rk
      real(rk), intent(in) :: x(:)
      real(rk), intent(out) :: g(:)
      class(*), intent(in) :: arg
    end subroutine
    pure subroutine eq_const_intrf(x,arg,ce)
      import :: rk
      real(rk), intent(in) :: x(:)
      class(*), intent(in) :: arg
      real(rk), intent(out) :: ce(:)
    end subroutine
    pure subroutine ieq_const_intrf(x,arg,ci)
      import :: rk
      real(rk), intent(in) :: x(:)
      class(*), intent(in) :: arg
      real(rk), intent(out) :: ci(:)
    end subroutine
  end interface

  interface l_bfgs_b
    module procedure :: l_bfgs_b
    module procedure :: l_bfgs_b_al_eq_const
    module procedure :: l_bfgs_b_al_ieq_const
  end interface

contains

  subroutine l_bfgs_b(x,lb,ub,func,grad,factr,pgtol,iprint,nbd,m)
    real(rk), intent(inout) :: x(:)
!     x is a REAL array of length n.  On initial entry
!       it must be set by the user to the values of the initial
!       estimate of the solution vector.  Upon successful exit, it
!       contains the values of the variables at the best point
!       found (usually an approximate solution).
    real(rk), intent(in) :: lb(:)
!     lb is an array of length n that must be set by
!       the user to the values of the lower bounds on the variables. If
!       the i-th variable has no lower bound, l(i) need not be defined.
    real(rk), intent(in) :: ub(:)
!     ub is a REAL array of length n that must be set by
!       the user to the values of the upper bounds on the variables. If
!       the i-th variable has no upper bound, u(i) need not be defined.
    procedure(func_intrf) :: func
!     func is a pure function to be minimized.
    procedure(grad_intrf) :: grad
!     grad is a pure subroutne to determine gradient of func.
    real(rk), optional, intent(in) :: factr
    real(rk) :: factr_local
!     factr is a REAL variable that must be set by the user.
!       It is a tolerance in the termination test for the algorithm.
!       The iteration will stop when
!
!        (f^k - f^{k+1})/max{|f^k|,|f^{k+1}|,1} <= factr*epsmch
!
!       where epsmch is the machine precision which is automatically
!       generated by the code. Typical values for factr on a computer
!       with 15 digits of accuracy in double precision are:
!       factr=1.d+12 for low accuracy;
!             1.d+7  for moderate accuracy;
!             1.d+1  for extremely high accuracy.
!       The user can suppress this termination test by setting factr=0.
    real(rk), optional, intent(in) :: pgtol
    real(rk) :: pgtol_local
!     pgtol is a REAL variable.
!       On entry pgtol >= 0 is specified by the user.  The iteration
!         will stop when
!
!                 max{|proj g_i | i = 1, ..., n} <= pgtol
!
!         where pg_i is the ith component of the projected gradient.
!       The user can suppress this termination test by setting pgtol=0.
    integer, optional, intent(in) :: iprint
    integer :: iprint_local
!     iprint is an INTEGER variable that must be set by the user.
!       It controls the frequency and type of output generated:
!        iprint<0    no output is generated;
!        iprint=0    print only one line at the last iteration;
!        0<iprint<99 print also f and |proj g| every iprint iterations;
!        iprint=99   print details of every iteration except n-vectors;
!        iprint=100  print also the changes of active set and final x;
!        iprint>100  print details of every iteration including x and g;
!       When iprint > 0, the file iterate.dat will be created to
!                        summarize the iteration.
    integer, optional, intent(in) :: nbd(:)
    integer, allocatable :: nbd_local(:)
!     nbd is an INTEGER array of dimension n that must be set by the
!       user to the type of bounds imposed on the variables:
!       nbd(i)=0 if x(i) is unbounded,
!              1 if x(i) has only a lower bound,
!              2 if x(i) has both lower and upper bounds,
!              3 if x(i) has only an upper bound.
    integer, optional, intent(in) :: m
    integer :: m_local
!     m is an INTEGER variable that must be set by the user to the
!       number of corrections used in the limited memory matrix.
!       It is not altered by the routine.  Values of m < 3  are
!       not recommended, and large values of m can result in excessive
!       computing time. The range  3 <= m <= 20 is recommended.
!-----------------------------Working variables---------------------------------
    real(rk), allocatable :: wa(:)
!     wa is a REAL array of length
!       (2mmax + 5)nmax + 11mmax^2 + 8mmax used as workspace.
    integer, allocatable :: iwa(:)
!     iwa is an INTEGER  array of length 3nmax used as
!       workspace. This array must not be altered by the user.
    character(len=60) :: task
!     task is a CHARACTER string of length 60.
!       On first entry, it must be set to 'START'.
!       On a return with task(1:2)='FG', the user must evaluate the
!         function f and gradient g at the returned value of x.
!       On a return with task(1:5)='NEW_X', an iteration of the
!         algorithm has concluded, and f and g contain f(x) and g(x)
!         respectively.  The user can decide whether to continue or stop
!         the iteration.
!       When
!         task(1:4)='CONV', the termination test in L-BFGS-B has been
!           satisfied;
!         task(1:4)='ABNO', the routine has terminated abnormally
!           without being able to satisfy the termination conditions,
!           x contains the best approximation found,
!           f and g contain f(x) and g(x) respectively;
!         task(1:5)='ERROR', the routine has detected an error in the
!           input parameters;
!       On exit with task = 'CONV', 'ABNO' or 'ERROR', the variable task
!         contains additional information that the user can print.
!       This array should not be altered unless the user wants to
!          stop the run for some reason.  See driver2 or driver3
!          for a detailed explanation on how to stop the run
!          by assigning task(1:4)='STOP' in the driver.
    character(len=60) :: csave
!     csave  is a CHARACTER working array of length 60.
    logical :: lsave(4)
!     lsave is a LOGICAL working array of dimension 4.
!       On exit with task = 'NEW_X', the following information is
!         available:
!       lsave(1) = .true.  the initial x did not satisfy the bounds;
!       lsave(2) = .true.  the problem contains bounds;
!       lsave(3) = .true.  each variable has upper and lower bounds.
    integer :: isave(44)
!     isave is an INTEGER working array of dimension 44.
!       On exit with task = 'NEW_X', it contains information that
!       the user may want to access:
!         isave(30) = the current iteration number;
!         isave(34) = the total number of function and gradient
!                         evaluations;
!         isave(36) = the number of function value or gradient
!                                  evaluations in the current iteration;
!         isave(38) = the number of free variables in the current
!                         iteration;
!         isave(39) = the number of active constraints at the current
!                         iteration;
    real(rk) :: dsave(29)
!     dsave is a DOUBLE PRECISION working array of dimension 29.
!       On exit with task = 'NEW_X', it contains information that
!         the user may want to access:
!         dsave(2)  = the value of f at the previous iteration;
!         dsave(5)  = the machine precision epsmch generated by the code;
!         dsave(13) = the infinity norm of the projected gradient;
!-------------------------------------------------------------------------------
    integer :: n ! number of variables
!------------------------Take care of optional arguments------------------------
    if (.not.present(factr)) then
      factr_local = 1.e+7_rk  ! for moderate accuracy
    else
      factr_local = factr
    end if
    if (.not.present(pgtol)) then
      pgtol_local = 1.e-5_rk
    else
      pgtol_local = pgtol
    end if
    if (.not.present(iprint)) then
      iprint_local = 0
    else
      iprint_local = iprint ! Print only one line at the last iteration
    end if
    if (.not.present(nbd)) then
      allocate(nbd_local(n),source=2) ! Both lower and upper bounds
    else
      nbd_local = nbd
    end if
    if (.not.present(m)) then
      m_local = 7 ! Modernate number of corrections
    else
      m_local = m
    end if




  end subroutine



  subroutine l_bfgs_b_al_eq_const(m,bris)
    integer, optional, intent(in) :: m
    integer, intent(in) :: bris


  end subroutine

  subroutine l_bfgs_b_al_ieq_const(m,bris1,bris2)
    integer, optional, intent(in) :: m
    integer, intent(in) :: bris1,bris2

  end subroutine


end module
